### PR TITLE
345 - fix for startHeadlessService() crash

### LINKED ISSUE #345: URGENT: 0.13.4 crashing after audio plays on iOS
- 0.13.3 had random crash on iOS app start
- 0.13.4 fixed random crash on iOS app start (yay!)
- 0.13.4 crash after audio plays on iOS (boo!)

I hope this issue can be resolved asap. Thanks!!

### PR DESCRIPTION
**Pull request by JesseScott**
#### :ticket: Issue

- https://github.com/luanpotter/audioplayers/issues/345

#### :grey_question:  What does this PR do?

- Fixes #345 by wrapping call to `"audio.onNotificationBackgroundPlayerStateChanged"` in a conditional that is only set by the proper method being called that would ensure that the FlutterEngine has properly registered the handler

#### :globe_with_meridians:  Where should the reviewer start?

- `ios/Classes/AudioplayersPlugin.m`

#### :microscope:  How should this be manually tested?

- Run the example app
  -- comment out the call to `_audioPlayer.startHeadlessService();` in `player_widget.dart`

#### :notebook:  Any background context you want to provide?

- 😅 been a long time since i had to code **Objective-C** 

#### :camera:  Screenshots / Screencasts

 - N/A

#### :sparkles:  What gif best describes this PR or how it makes you feel?

- https://media.giphy.com/media/39vl0ey26JznsznUHm/giphy.gif

#### :white_check_mark: Test Results

- Tests pass, but no new ones added

### CODE REVIEW

File: example/lib/main.dart [hunk 1]
```diff
@@ -30,6 +30,18 @@ class _ExampleAppState extends State<ExampleApp> {
...
+  void initState() {
+    super.initState();
+
+    if (Platform.isIOS) {
+      if (audioCache.fixedPlayer != null) {
+        audioCache.fixedPlayer.startHeadlessService();
+      }
+      advancedPlayer.startHeadlessService();
+    }
+  }
```
Comment (JesseScott) [inline example/lib/main.dart]: ☝️ not technically necessary but wanted to bring attention to the API call

File: example/lib/player_widget.dart [hunk 2]
```diff
@@ -132,7 +132,10 @@ class _PlayerWidgetState extends State<PlayerWidget> {
 
       // TODO implemented for iOS, waiting for android impl
       if (Theme.of(context).platform == TargetPlatform.iOS) {
-        // set atleast title to see the notification bar on ios.
+        // (Optional) listen for notification updates in the background
+        _audioPlayer.startHeadlessService();
```
Comment (JesseScott) [inline example/lib/player_widget.dart]: ☝️ again, not technically necessary but wanted to bring attention to the API call
(and actually I think that this call would be the only one that is necessary, the one in `main` isn't...)

File: ios/Classes/AudioplayersPlugin.m [hunk 3]
```diff
@@ -678,7 +681,7 @@ - (void)destory {
 }
     
 - (void)dealloc {
-    [self destory];
+    [self destroy];
```
Comment (JesseScott) [inline ios/Classes/AudioplayersPlugin.m]: this was bugging me 😄

File: ios/Classes/AudioplayersPlugin.m [hunk 4]
```diff
@@ -663,7 +666,7 @@ -(void)observeValueForKeyPath:(NSString *)keyPath
   }
 }
 
-- (void)destory {
+- (void)destroy {
```
Comment (JesseScott) [inline ios/Classes/AudioplayersPlugin.m]: this was bugging me 😄

File: ios/Classes/AudioplayersPlugin.m [hunk 5]
```diff
@@ -628,7 +629,9 @@ -(void) onSoundComplete: (NSString *) playerId {
   }
 
   [ _channel_audioplayer invokeMethod:@"audio.onComplete" arguments:@{@"playerId": playerId}];
-  [_callbackChannel invokeMethod:@"audio.onNotificationBackgroundPlayerStateChanged" arguments:@{@"playerId": playerId, @"updateHandleMonitorKey": @(_updateHandleMonitorKey), @"value": @"completed"}];
+  if (headlessServiceInitialized) {
+      [_callbackChannel invokeMethod:@"audio.onNotificationBackgroundPlayerStateChanged" arguments:@{@"playerId": playerId, @"updateHandleMonitorKey": @(_updateHandleMonitorKey), @"value": @"completed"}];
+  }
```
Comment (JesseScott) [inline ios/Classes/AudioplayersPlugin.m]: ☝️ main fix here... if the boolean isn't set by a successful result of `_headlessEngine. runWithEntrypoint:entrypoint` being called, meaning that the `_registrar` will not know how to handle this method, then don't call it...

File: lib/audioplayers.dart [hunk 6]
```diff
@@ -298,6 +298,9 @@ class AudioPlayer {
   /// this should be called after initiating AudioPlayer only if you want to
   /// listen for notification changes in the background
   void startHeadlessService() {
+    if (this == null || playerId.isEmpty) {
+      return;
+    }
```
Comment (JesseScott) [inline lib/audioplayers.dart]: ☝️ just being safe, saw this error out when trying to call `AudioCache.fixedPlayer.startHeadlessService()` on a null `fixedPlayer`...

**Comment by JesseScott** [comment]
> I am not sure about the changes on the example app, but I don't mind them.

... yeah, i understand, probably unnecessary now that it's safe to use w/o the API call, but still think it's an unknown method, so good to promote it...

**Comment by surrenderios** [comment]
I think you missed "onNotificationBackgroundPlayerStateChanged" in method playOrPauseEvent,
when user click pause, method playOrPauseEvent will call 

`[_callbackChannel invokeMethod:@"audio.onNotificationBackgroundPlayerStateChanged" arguments:@{@"playerId": _currentPlayerId, @"updateHandleMonitorKey": @(_updateHandleMonitorKey), @"value": playerState}];
` 

where also should be change to 

`
#if TARGET_OS_IPHONE
          if (headlessServiceInitialized) {
              [_callbackChannel invokeMethod:@"audio.onNotificationBackgroundPlayerStateChanged" arguments:@{@"playerId": _currentPlayerId, @"updateHandleMonitorKey": @(_updateHandleMonitorKey), @"value": playerState}];
              }
          #endif
`

I meet this crash when it is lock screen, I click pause button.
